version: "3.1"
name: "webproject"

services:
  app:
    image: "webproject_library"
    ports:
      - "80:80"
    depends_on:
      database:
        condition: "service_started"
    build:
      context: "."
      dockerfile: "Dockerfile"
  database:
    image: "mysql:8.0.31"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "webproject_library"
    volumes:
      - db_store:/var/lib/mysql
      - ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql

volumes:
  db_store:
