version: "3.1"
name: "webproject"

services:
  app:
    image: "webproject_library"
    ports:
      - "80:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      database:
        condition: "service_started"
    build:
      context: "."
      dockerfile: "Dockerfile"
  database:
    image: "mysql:8.0.31"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_store:/var/lib/mysql
      - ./database_init.sql:/docker-entrypoint-initdb.d/database_init.sql

volumes:
  db_store:
