name: Deploy website

on:
  push:
    branches:
      - main

jobs:
  transfer-files:
    name: Transfer files
    runs-on: ubuntu-latest
    steps:
      # Previous run clean
      - name: Clean the previous runs
        uses: AutoModality/action-clean@v1
      
      # Checkout the current code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
      
      # Transfer the code
      - name: Transfer files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./
          target: ~/webproject_library/
          rm: true
  
  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest
    needs: transfer-files
    steps:
      - name: "Starting deploy.sh"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ./webproject_library
            bash deploy.sh
        